# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('login', models.CharField(max_length=255)),
                ('password_encrypted', models.CharField(blank=True, max_length=255)),
                ('password_encrypted_iv', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'ggbot_account',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('room_password', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'ggbot_league',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'ggbot_room',
            },
        ),
        migrations.AddField(
            model_name='league',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggbot.Room'),
        ),
        migrations.AddField(
            model_name='account',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ggbot.League'),
        ),
    ]
