# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField()),
            ],
            options={
                'db_table': 'ggbot_account',
            },
        ),
    ]
